version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: "0"
    links:
      - influxdb
